apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-tracker-config
data:
  GIN_MODE: "release"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "migration_user"
  DB_NAME: "migration_tracker"
  # CÁLCULO: Se o banco aceita 100 conexões e teremos 4 réplicas: 100 / 4 = 25
  DB_MAX_OPEN_CONNS: "20" # Deixamos uma margem de segurança
  DB_MAX_IDLE_CONNS: "5"