apiVersion: batch/v1
kind: Job
metadata:
  name: migration-tracker-seed-catalog
  labels:
    app: migration-tracker-seed-catalog
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-seed-catalog
        image: quay.io/lagomes/migration-tracker-api:latest
        workingDir: /app
        command: 
        - "./admin-cli"
        - "-seed-catalog"
        envFrom:
        - configMapRef:
            name: migration-tracker-config
        - secretRef:
            name: migration-tracker-secrets
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      backoffLimit: 3

