apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: migration-tracker-api
  labels:
    app: migration-tracker-api
spec:
  to:
    kind: Service
    name: migration-tracker-api
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

