apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: migration-tracker-uat

resources:
  - namespace.yml
  - ../../base
  - ../../base/jobs/seed-fake

namePrefix: uat-

commonLabels:
  environment: uat

images:
  - name: quay.io/lagomes/migration-tracker-api
    newTag: v1.4

replicas:
  - name: migration-tracker-api
    count: 2
  - name: migration-tracker-postgres
    count: 1

patchesStrategicMerge:
  - deployment-patch.yml
  - route-patch.yml

